name: Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  workflow_dispatch:

env:
  NODE_VERSION: 18.13

jobs:
  publish:
    runs-on: ubuntu-20.04
    env:
      NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm run -r build

      - name: Publish
        if: github.ref == 'refs/heads/main'
        run: pnpm changeset publish

